#
# Build environment
#
FROM node:8.11.3 as builder

WORKDIR /detector_app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json .
RUN npm install
RUN npm install -g @angular/cli

COPY tslint.json tslint.json
COPY tsconfig.json tsconfig.json
COPY .angular-cli.json .
COPY e2e e2e
COPY src src

RUN npm run build

#
# Production
#

FROM nginx:1.13.9-alpine

COPY --from=builder /detector_app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
